#!/bin/sh
#
# List installed packages in a suitable format for GTK tree.
# List mirrored packages using the packages.desc file.
#

undigest_list()
{
	IFS="|"
	if [ -n "$1" -a "$1" != "all" ]; then
		cat /var/lib/tazpkg/undigest/$1/packages.desc
	else
		cat /var/lib/tazpkg/undigest/*/packages.desc
	fi 2> /dev/null | sort | while read PACKAGE VERSION SHORT_DESC; do
		echo "$PACKAGE|$VERSION|$SHORT_DESC"
	done
	unset IFS
}

installable_list()
{
	IFS="|"
	cat /var/lib/tazpkg/packages.desc \
	    /var/lib/tazpkg/undigest/*/packages.desc 2> /dev/null | sort | \
	while read PACKAGE VERSION SHORT_DESC; do
		# Check first for category for more speed.
		CATEGORY=${CATEGORY%| *}
		if [ "$CAT" == "all" ] || [ "$CATEGORY" == " $CAT " ]; then
			[ -d /var/lib/tazpkg/installed/${PACKAGE%% *} ] && continue
			echo "tazpkg|$PACKAGE|$VERSION|$SHORT_DESC"
		fi
	done
	unset IFS
}

installed_list()
{
	for pkg in /var/lib/tazpkg/installed/*
	do
		. $pkg/receipt
		if [ "$CAT" == "all" -o "$CATEGORY" == "$CAT" ]; then
			echo "tazpkg-installed|$PACKAGE|$VERSION|$SHORT_DESC"
		fi
	done
}

all_list()
{
	IFS="|"
	cat /var/lib/tazpkg/packages.desc \
	    /var/lib/tazpkg/undigest/*/packages.desc 2> /dev/null | sort | \
	while read PACKAGE VERSION SHORT_DESC CATEGORY; do
	# Check first for category for more speed.
	CATEGORY=${CATEGORY%| *}
	if [ "$CAT" == "all" ] || [ "$CATEGORY" == " $CAT " ]; then
		if [ -d /var/lib/tazpkg/installed/${PACKAGE%% *} ]; then
			. /var/lib/tazpkg/installed/${PACKAGE%% *}/receipt
			echo "tazpkg-installed|$PACKAGE|$VERSION|$SHORT_DESC"
		else
			echo "tazpkg|$PACKAGE|$VERSION|$SHORT_DESC"
		fi
	fi
	done
	unset IFS
}

blocked_list()
{
	for pkg in /var/lib/tazpkg/installed/*
	do
		. $pkg/receipt
		if grep -qs "^$(basename $pkg)$" /var/lib/tazpkg/blocked-packages.list; then
			AVAILABLE=$(grep "^$(basename $pkg) " /var/lib/tazpkg/packages.desc | awk '{ print $3 }')
			echo "stop|$PACKAGE|$VERSION (Available: $AVAILABLE)|$SHORT_DESC"
		fi
	done
}

case $1 in
	all)
		STATUS=`cat /tmp/tazpkgbox/status`
		case $STATUS in
			blocked)
				blocked_list ;;
			installed)
				CAT=`cat /tmp/tazpkgbox/category`
				installed_list ;;
			installable)
				CAT=`cat /tmp/tazpkgbox/category`
				installable_list ;;
			*)
				CAT=`cat /tmp/tazpkgbox/category`
				all_list ;;
		esac ;;
	undigest)
		set -- `cat /tmp/tazpkgbox/undigest-category`
		if [ "$1" == "all" -o "$1" == "" ]; then
			undigest_list $2
		else
			undigest_list $2 | grep "$1"
		fi ;;
	blocked)
		blocked_list ;;
	*)
		echo "Usage: $0 [all|undigest|blocked]" ;;
esac

exit 0
