#!/bin/sh
#
# Dialog box to provide package info and actions
#

XTERM_OPTS="-geometry 80x16+120+120"

PKG=`cat /tmp/tazpkgbox/pkg | sed s/" "/""/g`
TMP_DIR=/tmp/tazpkg-$$-$RANDOM

if [ "$1" = "list_files" ]; then
	AWK_FILTER='BEGIN { ls=0 } { if (/^===/) ls=1-ls; else if (ls) print; }'
	CONF_FILES="$(tazpkg list-config $2 | awk "$AWK_FILTER")"
	if [ -n "$CONF_FILES" ]; then
		mkdir $TMP_DIR
		zcat /var/lib/tazpkg/installed/$2/volatile.cpio.gz | \
			( cd $TMP_DIR ; cpio -id > /dev/null )
	fi
	tazpkg list-files $2 | awk "$AWK_FILTER" | while read file; do
		echo -n "$(stat -c "%A|%U|%G|%s|%n|" "$file")"
		if [ -L "$file" ]; then
			echo -n "$(readlink "$file")"
		elif [ -f "$file" ]; then
			case "$CONF_FILES" in
			*$file*) 
				if cmp $file $TMP_DIR$file > /dev/null 2>&1; then
					echo -n "[configuration]"
				else
					echo -n "$(stat -c "[configuration: %.16y]" $file)"
				fi;;
			esac
		fi
		echo ""
	done
	[ -n "$CONF_FILES" ] && rm -rf $TMP_DIR
	exit 0
fi

if [ "$1" = "list_files_mirror" ]; then
	unlzma -c /var/lib/tazpkg/files.list.lzma | grep -- "^$2:" | \
		awk '{ print substr($0,index($0,":")+2) }'
	exit 0
fi

export LIST_FILES="
<window title=\"$PKG files\" icon-name=\"system-file-manager\">
  <vbox>
	<tree exported_column=\"4\">
		<variable>FILE</variable>
		<width>600</width><height>160</height>
		<label>Access | User | Group | Size | Name | Target</label>
		<input> $0 list_files $PKG </input>
		<action>tazpkg list-config $PKG | grep -q ^\$FILE$ && leafpad \$FILE</action>
	</tree>
	<hbox>
		<button>
			<input file icon=\"gtk-close\"></input>
			<action type=\"closewindow\">INSTALLED_PACKAGE_ACTIONS</action>
		</button>
	</hbox>
  </vbox>
</window>
"

export LIST_FILES_MIRROR="
<window title=\"$PKG files\" icon-name=\"system-file-manager\">
  <vbox>
	<tree>
		<width>300</width><height>160</height>
		<label>File Name</label>
		<input> $0 list_files_mirror $PKG </input>
	</tree>
	<hbox>
		<button>
			<input file icon=\"gtk-close\"></input>
			<action type=\"closewindow\">INSTALLED_PACKAGE_ACTIONS</action>
		</button>
	</hbox>
  </vbox>
</window>
"

# Installed or not installed, that the question.
if [ -d /var/lib/tazpkg/installed/$PKG ]; then
	PACKED_SIZE=""
	DEPENDS=""
	MAINTAINER=""
	. /var/lib/tazpkg/installed/$PKG/receipt
	MAINTAINER=$(echo "$MAINTAINER" | sed 's/[<>|]/ /g')
	PACKAGE_INFOS="
<window title=\"Package: $PKG\" icon-name=\"package-x-generic\">
<vbox>

	<tree>
		<width>460</width><height>160</height>
		<label>$PKG|$SHORT_DESC</label>
		<variable>FIELD</variable>
		<item icon=\"tazpkg\">Version: | $VERSION</item>
		<item icon=\"tazpkg\">Category: | $CATEGORY</item>"
[ -n "$DEPENDS" ] && PACKAGE_INFOS="$PACKAGE_INFOS
		<item icon=\"tazpkg\">Depends: | $(echo $DEPENDS)</item>"
[ -n "$PACKED_SIZE" ] && PACKAGE_INFOS="$PACKAGE_INFOS
		<item icon=\"tazpkg\">Size: | $PACKED_SIZE ($UNPACKED_SIZE installed)</item>"
[ -n "$MAINTAINER" ] && PACKAGE_INFOS="$PACKAGE_INFOS
		<item icon=\"system-users\">Maintainer: | $MAINTAINER</item>"
PACKAGE_INFOS="$PACKAGE_INFOS
		<item icon=\"applications-internet\">Web site: | $WEB_SITE</item>
		<action>case \$FIELD in Web*) firefox $WEB_SITE &;; esac</action>
	</tree>

	<hbox>"
[ $CATEGORY = non-free -a ! -d /var/lib/tazpkg/installed/${PKG#get-} ] && PACKAGE_INFOS="$PACKAGE_INFOS
		<button>
			<label>Install</label>
			<input file icon=\"go-next\"></input>
			<action>xterm -T \"Install ${PKG#get-}\" $XTERM_OPTS -e \"\
			$PKG; sleep 5\"</action>
			<action type=\"closewindow\">INSTALLED_PACKAGE_ACTIONS</action>
		</button>"
grep -q post_install /var/lib/tazpkg/installed/$PKG/receipt && PACKAGE_INFOS="$PACKAGE_INFOS
		<button>
			<label>Reconfigure</label>
			<input file icon=\"reload\"></input>
			<action>xterm -T \"Reconfigure $PACKAGE\" $XTERM_OPTS -e \"\
			tazpkg reconfigure $PACKAGE; sleep 2\"</action>
			<action type=\"closewindow\">INSTALLED_PACKAGE_ACTIONS</action>
		</button>"
if grep -qs ^$PKG$ /var/lib/tazpkg/blocked-packages.list; then
	PACKAGE_INFOS="$PACKAGE_INFOS
		<button>
			<label>Unblock</label>
			<input file icon=\"up\"></input>
			<action>xterm -T \"Unblock $PACKAGE\" $XTERM_OPTS -e \"\
			tazpkg unblock $PACKAGE; sleep 2\"</action>
			<action type=\"closewindow\">INSTALLED_PACKAGE_ACTIONS</action>
		</button>"
else
	PACKAGE_INFOS="$PACKAGE_INFOS
		<button>
			<label>Block</label>
			<input file icon=\"down\"></input>
			<action>xterm -T \"Block $PACKAGE\" $XTERM_OPTS -e \"\
			tazpkg block $PACKAGE; sleep 2\"</action>
			<action type=\"closewindow\">INSTALLED_PACKAGE_ACTIONS</action>
		</button>"
fi
PACKAGE_INFOS="$PACKAGE_INFOS
		<button>
			<label>Remove</label>
			<input file icon=\"edit-delete\"></input>
			<action>xterm -T \"Remove $PACKAGE\" $XTERM_OPTS -e \"\
			tazpkg remove $PACKAGE; sleep 2\"</action>
			<action type=\"closewindow\">INSTALLED_PACKAGE_ACTIONS</action>
		</button>
		<button>
			<label>Repack</label>
			<input file icon=\"edit-redo\"></input>
			<action>xterm -T \"Repack $PACKAGE\" $XTERM_OPTS -e \"\
			cd /var/cache/tazpkg; \
			tazpkg repack $PACKAGE; sleep 2\"</action>
			<action type=\"closewindow\">INSTALLED_PACKAGE_ACTIONS</action>
		</button>
		<button>
			<label>Files</label>
			<input file icon=\"tazpkg\"></input>
			<action type=\"launch\">LIST_FILES</action>
		</button>
		<button>
			<input file icon=\"gtk-close\"></input>
			<action type=\"closewindow\">INSTALLED_PACKAGE_ACTIONS</action>
		</button>
	</hbox>

</vbox>
</window>
"
	export PACKAGE_INFOS
else
	RES=`grep "^$PKG" /var/lib/tazpkg/packages.desc | head -n 1`
	PACKAGE=`echo "$RES" | cut -d "|" -f 1`
	VERSION=`echo "$RES" | cut -d "|" -f 2`
	SHORT_DESC=`echo "$RES" | cut -d "|" -f 3`
	CATEGORY=`echo "$RES" | cut -d "|" -f 4`
	WEB_SITE=`echo "$RES" | cut -d "|" -f 5`
	SIZES=`grep -A 3 "^$(echo $PACKAGE)$" /var/lib/tazpkg/packages.txt | tail -1`
	PACKAGE_INFOS="
<window title=\"Package: $PACKAGE\" icon-name=\"package-x-generic\">
<vbox>

	<tree>
		<width>460</width><height>140</height>
		<label>$PKG|$SHORT_DESC</label>
		<item icon=\"tazpkg\">Name: | $PACKAGE</item>
		<item icon=\"tazpkg\">Version: | $VERSION</item>
		<item icon=\"tazpkg\">Category: | $CATEGORY</item>"
	[ -n "$SIZES" ] && PACKAGE_INFOS="$PACKAGE_INFOS
		<item icon=\"tazpkg\">Size: | $SIZES</item>"
	PACKAGE_INFOS="$PACKAGE_INFOS
		<item icon=\"applications-internet\">Web site: | $WEB_SITE</item>
	</tree>

	<hbox>"
	[ $CATEGORY = non-free ] && PACKAGE_INFOS="$PACKAGE_INFOS
		<checkbox>
			<label>Auto exec</label>
			<variable>AUTO_EXEC</variable>
			<default>true</default>
		</checkbox>"
	PACKAGE_INFOS="$PACKAGE_INFOS
		<checkbox>
			<label>Auto install depends</label>
			<variable>AUTO_DEPENDS</variable>
			<default>true</default>
		</checkbox>
		<button>
			<label>Get-install</label>
			<input file icon=\"go-next\"></input>
			<action>xterm -T \"Install $PACKAGE\" $XTERM_OPTS -e \"\
			if [ \$AUTO_DEPENDS != true ]; then tazpkg get-install $PACKAGE;\
			else yes y | tazpkg get-install $PACKAGE; fi; \
			[ \${AUTO_EXEC}$CATEGORY = truenon-free ] && $PACKAGE; \
			sleep 2\"</action>
			<action type=\"closewindow\">MIRRORED_PACKAGE_ACTIONS</action>
		</button>
		<button>
			<label>Get</label>
			<input file icon=\"go-next\"></input>
			<action>xterm -T \"Get $PACKAGE\" $XTERM_OPTS -e \"\
			cd /var/cache/tazpkg; tazpkg get $PACKAGE; sleep 2\"</action>
			<action type=\"closewindow\">MIRRORED_PACKAGE_ACTIONS</action>
		</button>
		<button>
			<label>Files</label>
			<input file icon=\"tazpkg\"></input>
			<action type=\"launch\">LIST_FILES_MIRROR</action>
		</button>
		<button>
			<input file icon=\"gtk-close\"></input>
			<action type=\"closewindow\">MIRRORED_PACKAGE_ACTIONS</action>
		</button>
	</hbox>

</vbox>
</window>
"
	export PACKAGE_INFOS
fi

gtkdialog --center --program=PACKAGE_INFOS

exit 0
