#!/bin/sh
#
# This script provide a suitable output for the search results.
#

# Clean preview results.
rm -f /tmp/tazpkgbox/search-installed
touch /tmp/tazpkgbox/search-installed

# Search installed.
for i in `ls /var/lib/tazpkg/installed`
do
	. /var/lib/tazpkg/installed/$i/receipt
	if echo "$PACKAGE $SHORT_DESC" | grep -q "$SEARCH"; then
		echo "$PACKAGE|$VERSION|$SHORT_DESC" >> /tmp/tazpkgbox/search-installed
	fi
done

# Search mirrored.
grep "$SEARCH" /var/lib/tazpkg/packages.desc > /tmp/tazpkgbox/search-mirrored

exit 0
