#!/bin/sh
# TazPkg - Tiny autonomous zone packages manager, hg.slitaz.org/tazpkg
# remove - TazPkg module
# Remove packages


# Connect function libraries
. /lib/libtaz.sh

# Get TazPkg working environment
. @@MODULES@@/getenv




# Log activity

log_pkg() {
	[ -w "$LOG" ] &&
	echo "$(date +'%F %T') - $1 - $PACKAGE ($VERSION$EXTRAVERSION)" >> "$LOG"
}


# Interactive mode

im() { tty -s; }


# Block of receipt function callers
# Why? "Bad" receipt sourcing can redefine some vital TazPkg variables.
# Few receipts function should be patched now.

# Input: $1 = path to the receipt to be processed

call_pre_remove() {
	local tmp
	if grep -q '^pre_remove()' "$1"; then
		action 'Execute pre-remove commands...'
		tmp="$(mktemp)"
		cp "$1" "$tmp"
		sed -i 's|$1/*$INSTALLED|$INSTALLED|g' "$tmp"
		( . "$tmp"; pre_remove "$root" )
		status
		rm "$tmp"
	fi
}

call_post_remove() {
	local tmp
	if grep -q '^post_remove()' "$1"; then
		action 'Execute post-remove commands...'
		tmp="$(mktemp)"
		cp "$1" "$tmp"
		sed -i 's|$1/*$INSTALLED|$INSTALLED|g' "$tmp"
		( . "$tmp"; post_remove "$root" )
		status
		rm "$tmp"
	fi
}




PACKAGE="$1"

if [ ! -f "$INSTALLED/$PACKAGE/receipt" ]; then
	newline; _ 'Package "%s" is not installed.' "$PACKAGE"
	exit 1
fi

. "$INSTALLED/$PACKAGE/receipt"

# Info #1: dependent packages (to be processed later)
ALTERED="$(awk -F$'\t' -vp=" $PACKAGE " 'index(" " $8 " ", p) { printf "  %s\n", $1 }' "$PKGS_DB/installed.info")"

if [ -n "$ALTERED" ]; then
	_ 'The following packages depend on package "%s":' "$PACKAGE"
	echo "$ALTERED"
fi

# Info #2: changed packages (to be processed later)
REFRESH=$(cd "$INSTALLED"; grep -sl "^$PACKAGE$" */modifiers)

if [ -n "$REFRESH" ]; then
	_ 'The following packages have been modified by package "%s":' "$PACKAGE"
	for i in $REFRESH; do
		echo "  ${i%/modifiers}"
	done
fi

# Confirmation
if im && [ -z "$auto" ]; then
	confirm "$(_ 'Remove package "%s" (%s)? (y/N)' "$PACKAGE" "$VERSION$EXTRAVERSION")"
	if [ "$?" -ne 0 ]; then
		newline; _ 'Uninstallation of package "%s" cancelled.' "$PACKAGE"
		exit 0
	fi
fi
# We are here: non-interactive mode, or --auto, or answer 'y'

# Removing package
title 'Removing package "%s"' "$PACKAGE"

# [1/4] Pre-remove commands
call_pre_remove "$INSTALLED/$PACKAGE/receipt"


# [2/4] Removing files
action 'Removing all files installed...'

# NOTE: package 'faenza-icon-theme' install time: 12s; removing time ~ 11min on my system  o_O
# After optimization: 6s! (Long) for-loops are (big) evil ;)

# NOTE: many packages contains filenames with spaces:
#   lzcat /var/lib/tazpkg/files.list.lzma | awk -F" " '{if(NF>2)print $1}' | sed 's|:$||' | uniq
# Redefine IFS to only-new-line field separator:
IFS=$'\n'

files2remove="$(mktemp)"
dirs2remove="$(mktemp)"

debug '\nDetermine which files to remove...'
if [ -f "$INSTALLED/$PACKAGE/modifiers" ]; then
	debug '  (modifiers detected)'

	mods="$(mktemp)"
	for mod in $(cat "$INSTALLED/$PACKAGE/modifiers"); do
		cat "$INSTALLED/$mod/files.list" >> "$mods" 2>/dev/null
	done

	awk -vroot="$root" -vfl="$INSTALLED/$PACKAGE/files.list" '
	{
		if (FILENAME == fl)
			f[$0] = 1;
		else
			f[$0] = "";
	}
	END {
		for (i in f) {
			if (f[i] == 1) printf "%s%s\n", root, i;
		}
	}' "$INSTALLED/$PACKAGE/files.list" "$mods" > "$files2remove"
	rm "$mods"
else
	debug '  (modifiers not detected)'

	awk -vroot="$root" '{ printf "%s%s\n", root, $0; }' \
		"$INSTALLED/$PACKAGE/files.list" > "$files2remove"
fi

debug 'Removing files...'
xargs rm -f < "$files2remove"

debug 'Determine which folders to remove...'
awk '
BEGIN {
	FS = "/"; OFS = "/";
}
{
	# removing filename beyond the last "/"
	$NF = "";
	if (! a[$0]) {
		a[$0] = 1; print;
	}
}' "$files2remove" | sed 's|/$||' > "$dirs2remove"

debug 'Removing folders...'
for dir2r in $(cat "$dirs2remove"); do
	dir="$dir2r"
	while [ -n "$dir" ]; do
		rmdir "$dir" 2>/dev/null || break
		dir="${dir%/*}"
	done
done
rm "$files2remove" "$dirs2remove"
unset IFS

status

# [3/4] Post-remove commands
call_post_remove "$INSTALLED/$PACKAGE/receipt"

# [4/4] Remove package receipt and remove it from databases
action 'Removing package receipt...'
rm -rf "$INSTALLED/$PACKAGE"
sed -i "/ $PACKAGE-$VERSION$EXTRAVERSION.tazpkg$/d" "$PKGS_DB/installed.$SUM"
sed -i "/^$PACKAGE	/d" "$PKGS_DB/installed.info"
status

footer "$(_ 'Package "%s" (%s) removed.' "$PACKAGE" "$VERSION$EXTRAVERSION")"

# Log this activity
log_pkg Removed

# Stop if non-interactive mode and no --auto option
if ! im && [ -z "$auto" ]; then exit 0; fi

# Process dependent packages
if [ -n "$ALTERED" ]; then
	if [ -n "$auto" ]; then
		answer=0
	else
		confirm "$(_ 'Remove packages depending on package "%s"? (y/N)' "$PACKAGE")"
		answer=$?
	fi
	if [ "$answer" -eq 0 ]; then
		for i in $ALTERED; do
			if [ -d "$INSTALLED/$i" ]; then
				tazpkg remove $i
			fi
		done
	fi
fi

# Process changed packages
if [ -n "$REFRESH" ]; then
	if [ -n "$auto" ]; then
		answer=0
	else
		confirm "$(_ 'Reinstall packages modified by package "%s"? (y/N)' "$PACKAGE")"
		answer=$?
	fi
	if [ "$answer" -eq 0 ]; then
		for i in $REFRESH; do
			if [ "$(wc -l < "$INSTALLED/$i")" -gt 1 ]; then
				_ 'Package "%s" was modified by "%s" and other packages. It will not be reinstalled.' \
					"${i%/modifiers}" "$PACKAGE"
				_ 'Check "%s" for reinstallation.' "$INSTALLED/$i"

				continue
			fi
			rm -r "$INSTALLED/$i"
			tazpkg get-install ${i%/modifiers} --forced
		done
	fi
fi

