#!/bin/sh
#
# Small GTK boxes to TazPKG for deep desktop integration. PcmanFM 0.5.x has a
# patch to extract a TazPKG file but not Thunar and other FM. TazPKGbox tries
# to follow freedesktop standards.
#
# Copyright (C) 2012 SliTaz GNU/Linux - GNU gpl v2
#
# Authors : Christophe Lincoln <pankso@slitaz.org>
#

# Internationalization.
. /usr/bin/gettext.sh
TEXTDOMAIN='tazpkg'
export TEXTDOMAIN

title=$(gettext "TazPKG Action")
icon="/usr/share/pixmaps/tazpkg.png"
opts="--image=tazpkg --image-on-top --width=520 --center --on-top"

# Nice GTK output for install and extract.
output() {
	yad --text-info $opts --text="<b>$title</b>" \
		--height=260 --title="$title" --window-icon=$icon \
		--tail --margins=4 --button="gtk-close:0"
}

# Main GUI box function with pure Yad spec
actions_main() {
	pkgname=${pkg%.tazpkg}
	text=$(eval_gettext 'Package name: <b>$pkgname</b>')
	yad --text="$text" $opts \
		--title="$title" --height=100 \
		--window-icon=$icon --image-on-top \
		--button="$(gettext 'Install'):3" --button="$(gettext 'Extract'):2" \
		--button="gtk-close:1"
}

# Actions user can do when clicking on a package.
actions() {
	# Store box results
	main=$(actions_main)
	ret=$?
	# Deal with --button values
	case $ret in
		1) exit 0 ;;
		2) tazpkg extract $pkg . --output="raw" | output ;;
		3) tazpkg -i $pkg . --forced --output="raw" | output ;;
	esac
}

# TazPKG URL Handler.
dl_inst() {
	pkg=$(basename $url) 
	eval_gettext "Downloading: \$pkg"; echo -e "\n"
	cd /tmp && wget $url 2>&1
	tazpkg -i $pkg --forced --output="raw" 2>&1
	rm -f $pkg
}

#
# Script commands
#

case "$1" in
	usage|help|-u|-h)
		progname=$(basename $0)
		eval_gettext "Usage: \$progname [actions|url] [pkg]" ;;
	tazpkg://*)
		# TazPKG URL's handler.
		url="http://${1#tazpkg://}"
		dl_inst | output ;;
	actions)
		pkg=$(basename $2)
		cd $(dirname $2)
		actions ;;
esac

exit 0

