#!/bin/sh
# TazPkg - Tiny autonomous zone packages manager, hg.slitaz.org/tazpkg
# tazpkg-notify - part of TazPkg
# Notification icon for TazPkg packages

# Recharging pkgs list can be done automatically at boot, so notifies users
# if some updates are available. Also notifies users if the packages list is too
# old and out-of-date or if no packages list found. This script should
# be run by the WM autostart script or ~/.xsession and needs a systray to
# sit in like in LXpanel or Tint2.

# Copyright (C) 2012-2015 SliTaz - GNU General Public License v3.
# Authors: See the AUTHORS files


. /lib/libtaz.sh
. /etc/slitaz/slitaz.conf

# I18n
export TEXTDOMAIN='tazpkg'

fifo=/tmp/$(basename $0).fifo
doc="file:///usr/share/doc/tazpkg/tazpkg.html"

installed=$(wc -l < "$PKGS_DB/installed.info")
text="$(_p \
		'%s installed package' \
		'%s installed packages' "$installed" \
		"<b>$installed</b>")"

[ -f "$PKGS_DB/IDs" ] && mtime=$(find "$PKGS_DB/IDs" -mtime +10;)
up=0; [ -f "$PKGS_DB/packages.up" ] && up=$(wc -l < "$PKGS_DB/packages.up")


# Notification icon

listen() {
	# Manage the I/O redirection from SHell
	rm -f $fifo; mkfifo $fifo

	# Attach a file descriptor
	exec 3<> $fifo

	# Notification icon
	yad --notification --listen --image='software-update-available' \
		--text="$(_ 'Checking packages lists - %s' "$text")" <&3

	# Clean-up
	rm -f $fifo
}


# Notification menu (right click)

menu() {
	cat << EOT
menu:\
$(_n 'My packages'       )!tazpanel pkgs#list!package-x-generic|\
$(_n 'Recharge lists'    )!tazbox su tazpanel pkgs#recharge!system-software-update|\
$(_n 'Check upgrade'     )!tazbox su tazpanel pkgs#up!system-software-install|\
$(_n 'TazPkg SHell'      )!terminal -e tazpkg shell!utilities-terminal|\
$(_n 'TazPkg manual'     )!tazweb --notoolbar $doc!slitaz-doc|\
$(_n 'Close notification')!quit!gtk-close
EOT
}


case $1 in
	usage|help|*-h)
		_n "Usage:"; echo " $(basename $0)"
		;;
	*)
		# Sleep before displaying the notification icon and
		# sleep to let user read the tooltips.
		sleep 4
		listen &
		sleep 2
		menu > $fifo
		sleep 6

		# Missing packages list
		if [ ! -f "$PKGS_DB/packages.info" ]; then
			tooltip="$(_ 'No packages list found - %s' "$text")"
			(echo "action:tazbox su tazpanel pkgs#recharge"
			 echo "tooltip:$tooltip"
			 echo "icon:software-update-urgent") > $fifo
			exit 0
		fi

		# Too old packages list
		if [ -n "$mtime" ]; then
			tooltip="$(_ 'Your packages list is older than 10 days')"
			(echo "action:tazbox su tazpanel pkgs#recharge"
			 echo "action:quit"
			 echo "tooltip:$tooltip"
			 echo "icon:software-update-urgent") > $fifo
			exit 0
		fi

		# Available upgrades
		if [ "$up" -gt 0 ]; then
			tooltip="$(_p \
				'There is %s upgradeable package' \
				'There are %s upgradeable packages' "$up" \
				"<b>$up</b>")"
			(echo "action:tazbox su tazpanel pkgs#up"
			 echo "tooltip:$tooltip"
			 echo "icon:software-update-urgent") > $fifo
			exit 0
		fi

		# Nothing to do, close notification
		tooltip="$(_ 'System is up to date - %s' "$text")"
		echo "tooltip:$tooltip" > $fifo
		sleep 10
		echo "quit" > $fifo
		;;
esac
exit 0
