#!/bin/sh
#
# Small GTK boxes to TazPKG for deep desktop integration. PcmanFM 0.5.x has a
# patch to extract a TazPKG file but not Thunar and other FM. TazPKGbox tries
# to follow freedesktop standards.
#
# Copyright (C) 2012 SliTaz GNU/Linux - GNU gpl v2
#
# Authors : Christophe Lincoln <pankso@slitaz.org>
#

title=$(gettext "TazPKG Action")
icon="/usr/share/pixmaps/tazpkg.png"
opts="--image=tazpkg --image-on-top --width=520 --center --on-top"

# Nice GTK output for install and extract.
output() {
	yad --text-info $opts --text="<b>$title</b>" \
		--height=260 --title="$title" --window-icon=$icon \
		--tail --margins=4 --button="gtk-close:0"
}

# Main GUI box function with pure Yad spec
actions_main() {
	text=$(gettext "Package name:")
	yad --text="$text <b>${pkg%.tazpkg}</b>" $opts \
		--title="$title" --height=100 \
		--window-icon=$icon --image-on-top \
		--button="Install:3" --button="Extract:2" \
		--button="gtk-close:1"
}

# Actions user can do when clicking on a package.
actions() {
	# Store box results
	main=$(actions_main)
	ret=$?
	# Deal with --button values
	case $ret in
		1) exit 0 ;;
		2) tazpkg extract $pkg | output ;;
		3) tazpkg -i $pkg --forced | output ;;
	esac
}

# TazPKG URL Handler.
dl_inst() {
	pkg=$(basename $url) 
	gettext "Downloading: $pkg"; echo -e "\n"
	cd /tmp && wget $url 2>&1
	tazpkg -i $pkg --forced 2>&1
	rm -f $pkg
}

#
# Script commands
#

case "$1" in
	usage|help|-u|-h)
		echo "Usage: $(basename $0) [actions|url] [pkg]" ;;
	tazpkg://*)
		# TazPKG URL's handler.
		url="http://${1#tazpkg://}"
		dl_inst | output ;;
	actions)
		pkg=$(basename $2)
		cd $(dirname $2)
		actions ;;
esac

exit 0

